### ISSUE TITLE
This is not a good description of your game

### ISSUE THREAD

**Issue by tu2** [CatX711/Coffee-Game#1]
IMPORTANT MESSAGE:

jdnaisdiasndasdasduasbdausduasduyasduyasdhaysdauysdhyayshduayshduaysdasuhusghisfjesfjsiudfhouheuyewgrvwuyergwuerguwernuwergvnuywnervnguwyergvuwernuwnyveuwyvenguynwergvnuwyervnguwyenvguwygvenruwnyrvnuwyevrgnudyngusegrvwuyrgvuedfvuyserguevuwenfijsndfksjdn COFFEE

**Comment by CatX711** [comment]
Well uhh... i mean- its coffee- coffee is right there in the description haha....

**Comment by CatX711** [comment]
Due to high demand the description has been changed.
